<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title></title>
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
   <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
   <script type="text/javascript" src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
</head>
<body>
	<nav class="navbar bg-body-tertiary">
  <form class="container-fluid justify-content-start">
    <a class="btn btn-outline-secondary" type="button" href="index.php?c=product&a=grid">Product</a>
    <a class="btn btn-outline-secondary" type="button" href="index.php?c=salesman&a=grid">Salesman</a>
    <a class="btn btn-outline-secondary" type="button" href="index.php?c=vendor&a=grid">Vendor</a>
    <a class="btn btn-outline-secondary" type="button" href="index.php?c=customer&a=grid">Customer</a>
    <a class="btn btn-outline-secondary" type="button" href="index.php?c=category&a=grid">Category</a>
    <a class="btn btn-outline-secondary" type="button" href="index.php?c=eav_attribute&a=grid">EAV</a>
  </form>
</nav>
</body>
</html>