<?php $attribute = $this->getAttribute(); ?>
<?php $options = $attribute->getOption(); 
$row = $this->getRow();
?>


<select name="attribute[<?php echo $attribute->backend_type;?>][<?php echo $attribute->getId();?>]">
	<option value="0">select</option>	
	<?php if ($options->count()>0):?>
	<?php foreach ($options->getData() as $option): ?>
		<?php $selected = ($row->getAttributeValue($attribute) == $option->option_id)? 'selected':''?>
	<option value = "<?php echo $option->option_id;?>"<?php echo $selected;?>><?php echo $option->name;?></option>
	<?php endforeach; ?>
<?php endif; ?>
</select>


