<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title></title>
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
   <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
</head>
<body>
	<table class="table table-striped">
		<tr>
			<td colspan="3"><?php $this->getChild('header')->render()?></td>
		</tr>
		<tr>
			<td colspan="3"><?php $this->getChild('message')->render()?></td>
		</tr>
		<tr>
			<td>left</td>
			<td><?php $this->getChild('content')->render()?></td>
		</tr>
		<tr >
			<td colspan="3">Footer</td>
		</tr>
	</table>
</body>
</html>